const AppImages = {
    BG: require('../images/Bg.png'),
    BGIMAGE: require('../images/BgImage.png'),
    PERSON1: require('../images/loginPerson.png'),
    PERSON2: require('../images/registerPerson.png'),
    EYE: require('../images/eye.png'),
    EYE_OFF: require('../images/eye-off.png'),
    FACEBOOK: require('../images/facebook.png'),
    GOOGLE: require('../images/google.png'),
    HOME: require('../images/home.png'),
    AD: require('../images/ad.png'),
    HEART_FILL: require('../images/heart.png'),
    HEART: require('../images/heart-line.png'),
    MENU: require('../images/menu.png'),
    ADD: require('../images/add.png'),
    SEARCH: require('../images/search.png'),
    ARROW_DOWN: require('../images/arrow-down.png'),
    ARROW_RIGHT: require('../images/arrow-right.png'),
    ARROW_LEFT: require('../images/arrow-left.png'),
    CIRCLE: require('../images/circle.png'),
    PLACEHOLDER: require('../images/placeholder-image.png'),
    RIGHT_ARROW: require('../images/right-arrow.png'),
    MASTER: require('../images/master.png'),
    VISA: require('../images/visa.png'),
    BANKING: require('../images/banking.png'),
    TRANSFER: require('../images/transfer.png'),
    SUCCESS: require('../images/success.png'),
    UPLOAD: require('../images/upload.png'),
    DELETE: require('../images/delete.png'),
    CALENDAR: require('../images/calendar.png'),
    CALL: require('../images/call.png'),
    CITY: require('../images/city.png'),
    ISSUE: require('../images/issue.png'),
    LANG: require('../images/lang.png'),
    MYADS: require('../images/myads.png'),
    PROFILE: require('../images/profile.png'),
    SUPPORT: require('../images/support.png'),
    LOCATION: require('../images/location.png'),
    CARD: require('../images/card.png'),
  };
  
  export default AppImages;