export const RouteNames = {
  WelcomeScreen: 'WelcomeScreen',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  OtpVerificationScreen:'OtpVerificationScreen',
  BottomTabs:'BottomTabs',
  AdsScreen:'AdsScreen',
  FavoritesScreen:'FavoritesScreen',
  HomeScreen:'HomeScreen',
  ProfileScreen:'ProfileScreen',
  PostListScreen:'PostListScreen',
  DetailsScreen:'DetailsScreen',
  CategoryListScreen:'CategoryListScreen',
  FilterScreen:'FilterScreen',
  PostSecondScreen:'PostSecondScreen',
  PlaceAdScreen:'PlaceAdScreen',
  CustomPlaceAd:'CustomPlaceAd',
  SellerInformation:'SellerInformation',
  PaymentScreen:'PaymentScreen',
  SuccessPage:'SuccessPage',
  MotorPlaceAd:'MotorPlaceAd',
  SaleRentPlaceAd:'SaleRentPlaceAd',
  MyJobProfile:'MyJobProfile',
  TermsAndConditions:'TermsAndConditions',
  MyJobDetails:'MyJobDetails',
  JobSearch:'JobSearch',
  JobApply:'JobApply',
  HiringListScreen:'HiringListScreen',
  EditProfile:'EditProfile'
} as const;
