export type RootStackParams = {
  SplashScreen: undefined;
  WelcomeScreen: undefined;
  LoginScreen: undefined;
  RegisterScreen: undefined;
  OtpVerificationScreen: undefined;
  BottomTabs: undefined;
  AdsScreen:undefined;
  FavoritesScreen:undefined;
  HomeScreen:undefined;
  ProfileScreen:undefined;
  PostListScreen:undefined;
  DetailsScreen:undefined;
  CategoryListScreen:undefined;
  FilterScreen:undefined;
  PostSecondScreen:undefined;
  PlaceAdScreen:undefined;
  CustomPlaceAd:undefined;
  SellerInformation:undefined;
  PaymentScreen:undefined;
  SuccessPage:undefined;
  MotorPlaceAd:undefined;
  SaleRentPlaceAd:undefined;
  MyJobProfile:undefined;
  TermsAndConditions:undefined;
  MyJobDetails:undefined;
  JobSearch: undefined;
  JobApply: undefined;
  HiringListScreen: undefined;
  EditProfile: undefined;
  HiringJobDetails: undefined;
  SearchListScreen: undefined;
  ForgotPasswordScreen: undefined;
  PasswordResetScreen: undefined;
};
